### ISSUE TITLE
what the source attribute label or target attribute label is?

### ISSUE THREAD

**Issue by GiggleLy** [megvii-research/FST-Matching#1]

**Comment by ceeyeo** [comment]
In the paper, the author said he used the identity of the image as the attribute. That is, for fake image, the source attribute is the identity of the source image, the target attribute is the identity of the target image, and for real image, the source attribute and target attribute are the same identity.

**Comment by GiggleLy** [comment]
> 



> In the paper, the author said he used the identity of the image as the attribute. That is, for fake image, the source attribute is the identity of the source image, the target attribute is the identity of the target image, and for real image, the source attribute and target attribute are the same identity.

Thank you for your reply, does that mean that the source label and target label are the identity ID of the image, and not just belong to [0,1] like the real and fake labels?

**Comment by Nku-cs-dsc** [comment]
The definition of source and target labels is essential for training encoders since they are designed to extract source-relevant (attribute) and target-relevant (ID) features from fake images. By training these two encoders, FST-Matching can extract artifact features by decoupling the source-target relevant features from the fake image.  This process can improve the model's robustness to image compression. 
For more details, please refer to the paper "Explaining Deepfake Detection by Analyzing Image Matching".
